# Generated by Django 3.1.7 on 2021-07-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_business_healthcenter_location_neighbour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='neighbour',
            name='image',
        ),
    ]
