# Generated by Django 3.1.7 on 2021-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_auto_20210726_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbour',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
