# Generated by Django 3.1.7 on 2021-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0006_auto_20210726_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbour',
            name='healthcenter',
        ),
        migrations.AlterField(
            model_name='healthcenter',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
