# Generated by Django 3.1.7 on 2021-07-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0009_auto_20210726_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
